dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'  
install:
  - pip install --upgrade setuptools
  - python setup.py install
  - pip uninstall -y nuts-finder
  - pip install -r requirements.txt
  - python -c "import sys; print(sys.path)"
script:
  - ./.travis/run.sh
branches:
  only:
    - master
