on:
  push:
    branches:
      - dev

jobs:
  make_tag:
    runs-on: ubuntu-latest
    name: Create a tag from dev

    # ----------------------------
    # Actions
    steps:
      # Checkout
      - name: Checkout the repo
        uses: actions/checkout@v2
      # Determine the tag
      - name: Extract the tag name from the VERSION file
        run: |
          TAG=$(cat ${{ github.event.repository.name }}/VERSION)
          echo "tag=${TAG}" >> $GITHUB_ENV
      # Create the tag
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.tag }}",
              sha: context.sha
            })
